services:
  backend:
    image: jayce90/weadopt-backend:v1
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONBUFFERED=1
    restart: always

  frontend:
    image: jayce90/weadopt-frontend:v1
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    restart: always

