name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    - name: Build and push frontend image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
